before:
  hooks:
    - go mod download
builds:
  - id: cj-killproxy
    binary: cj-killproxy
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

dockers:
  -
    image_templates:
    - "ghcr.io/arldka/{{ .ProjectName }}:latest"
    - "ghcr.io/arldka/{{ .ProjectName }}:{{ .Major }}"
    - "ghcr.io/arldka/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}"
    - "ghcr.io/arldka/{{ .ProjectName }}:{{ .Major }}.{{ .Minor }}.{{ .Patch }}"
    build_flag_templates:
    - "--pull"
    - "--label=org.opencontainers.image.created={{.Date}}"
    - "--label=org.opencontainers.image.name={{.ProjectName}}"
    - "--label=org.opencontainers.image.revision={{.FullCommit}}"
    - "--label=org.opencontainers.image.version={{.Version}}"
    - "--label=org.opencontainers.image.source={{.GitURL}}"